# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
- group: Dev variables


stages:

  - stage: buildpush
    jobs:
      - job: 
        steps:
        - task: Docker@2
          displayName: docker login
          inputs:
            containerRegistry: '$(registryname)'
            command: 'login'
        - task: Docker@2
          displayName: build and push
          inputs:
            containerRegistry: '$(registryname)'
            repository: '$(repoimage)'
            command: 'buildAndPush'
            tags: |
              latest
              $(Build.BuildId)
            Dockerfile: '**/Dockerfile'

  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'Friday'
              backendAzureRmResourceGroupName: '$(bergname)'
              backendAzureRmStorageAccountName: '$(besaname)'
              backendAzureRmContainerName: '$(becontainer)'
              backendAzureRmKey: '$(bekey)'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'

  - stage: plan
    displayName: plan
    jobs:
    - job: plan
      steps:
      - task: TerraformInstaller@0
        displayName: tfinstall
        inputs:
          terraformVersion: 'latest'

      - task: TerraformTaskV4@4
        displayName: init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
          backendServiceArm: 'Friday'
          backendAzureRmResourceGroupName: '$(bergname)'
          backendAzureRmStorageAccountName: '$(besaname)'
          backendAzureRmContainerName: '$(becontainer)'
          backendAzureRmKey: '$(bekey)'

  - stage: apply
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'Friday'
              backendAzureRmResourceGroupName: '$(bergname)'
              backendAzureRmStorageAccountName: '$(besaname)'
              backendAzureRmContainerName: '$(becontainer)'
              backendAzureRmKey: '$(bekey)'

          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'Friday'

          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'Friday'

  - stage: deploytodev
    displayName: deploy to dev
    jobs:
      - deployment: 
        pool:
          vmImage: "ubuntu-latest"
        environment: "Dev"
      - job:
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Friday'
              appType: 'webAppContainer'
              WebAppName: '$(appname)'
              DockerNamespace: '$(registryurl)'
              DockerRepository: '$(repoimage)'
              DockerImageTag: latest
              AppSettings: '-DOCKER_REGISTRY_SERVER_USERNAME $(dockeruser) -DOCKER_REGISTRY_SERVER_PASSWORD $(dockerpass)'