

trigger:
- develop

pool:
  vmImage: ubuntu-latest


stages:
  - stage: dockerbuild-dockerpush
    jobs:
      - job: dockerbuild-dockerpush
        steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
          command: login
          containerRegistry: dockerRegistryServiceConnection1
        - task: Docker@2
          displayName: buildpush
          inputs:
            containerRegistry: 'sxregistrytfdev'
            repository: 'sxregistrytfdev'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
