

trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:
  - stage: dockerbuildpush
    jobs:
      - job: dockerbuildpush
        steps:
        - task: Docker@2
          displayName: docker login
          inputs:
            containerRegistry: 'sxregistrytfdev'
            command: 'login'

        - task: Docker@2
          displayName: build and push
          inputs:
            containerRegistry: 'sxregistrytfdev'
            repository: 'sxtest'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
