

trigger:
- develop

pool:
  vmImage: ubuntu-latest


stages:
  - stage: dockerbuildpush
    jobs:
      - job: dockerbuildpush
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'sxregistrytfdev01'
            command: 'login'
        - task: Docker@2
          displayName: buildpush
          inputs:
            containerRegistry: 'sxregistrytfdev01'
            repository: 'sxtest'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
