

trigger:
- develop

pool:
  vmImage: ubuntu-latest


stages:
  - stage: dockerbuildpush
    jobs:
      - job: dockerbuildpush
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'sxregistrytfdev'
            repository: 'sxregistrytfdev'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
