

trigger:
- develop

pool:
  vmImage: ubuntu-latest


stages:
  - stage: dockerbuildpush
    jobs:
      - job: dockerbuildpush
        steps:
        - task: Docker@2
          displayName: Login to ACR
          inputs:
          command: login
          containerRegistry: 'sxregistrytfdev'
        - task: Docker@2
          displayName: buildpush
          inputs:
            containerRegistry: 'sxregistrytfdev'
            repository: 'sxregistrytfdev'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
